### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by declanmarks** [marlam/bino#1]
Any chance that you will update this application as their hasn't been any activity for a year. Its just that when opening a youtube url fails.

**Comment by marlam** [comment]
I will continue to fix bugs. But not supporting YouTube URLs is not a bug: that is simply not how YouTube or video players work. Try [youtube-dl](https://github.com/ytdl-org/youtube-dl) to get a proper video file from YouTube, then you can play it with Bino (or any other video player).
