### ISSUE TITLE
no sound in fullscreen

### ISSUE THREAD

**Issue by beew** [marlam/bino#10]
For all the samples from here (all have 6 audio channels) bino loses audio when go to fullscreen
https://www.demolandia.net/3d-video/brands/lg/page-3.html

The work around is to exit fullscreen, move the playback progress back a bit until sound is restored and then go to fullscreen again and then there is audio in fullscreen.

It is kind of annoying.

Same with both bino-1.6.6 from repository and bino-1.6.7 compiled from source.

OS is Ubuntu 20.04, graphic NVIDIA GTX1070

**Comment by marlam** [comment]
I cannot reproduce this on my machine (Debian unstable, LXQT).

**Comment by marlam** [comment]
Bino is currently being rewritten completely and will be based on Qt 6. The fullscreen mode is now based on standard Qt methods instead of low-level system fiddling. This should solve this issue. An initial version of the new Bino is already in the main git repository, you can try it.
