### ISSUE TITLE
Separate Streams for synchronized playback of two video files

### ISSUE THREAD

**Issue by porg** [marlam/bino#11]
## 👍 Praise
I love this feature though I use it a bit differently 😉 :

- Instead of using it for stereoscopic video playback coming from two separate source files I use this feature of Bino to open different export/transcoding qualities of the same video.
- Input is then: Separate streams
- Output: I set this to one of them (left) or display them side by side, or on top of each other, whatever uses the screen space better.
- Great! Though I don't know how reliable it is for spotting differences. I set the render level to the maximum of 4. Would this be enough for reliably spotting smaller encoding differences?

## 💡Improvement

Opening multiple files should not only work with using Menu > File > Open but also when opening multiple files via double click in Finder which are associated to open with Bino or via drag-n-drop onto Bino.app icon.

### Ability to set dedicated zoom factors
- CMD-0 Auto — This is currently the case
	- In addition Preferences > Zoom decides whether to fit or fill.
- CMD-1 "Original (100%)" — 1 source pixel is 1 presentation pixel, more reliable check for quality
- CMD-2 "Double Size (200%)" — 1 source pixel is 2 presentation pixels, see how upscaling works on a full multiple (also good for testing low vs.  high resolution (@2x) displays)
- Manual Zoom factor -> dialog which takes percent or fraction -> Cancel / Apply

### User Preference: Criteria for Separate Streams
- Currently Bino determines itself whether two files are suited as Input for "Separate Streams". From what I observed the criteria seem to be:
	- Length must be the same
	- Resolution must be the same
	- Container format must be the same
- It would be cool if power users could set those criteria themselves. Differences in:
	- **Container format**
		- Only offer this is possible. I do not compare different container formats anyhow. Some may want to use it for this.
	- **Length**
		- Ofc if video A ends then ofc only video B is played back until it ends. Totally ok with it.
	- **Resolution**
		- 3 settings:
			- Original size of both
			- Scale small one up to size of large one
			- Scale large one down to size of small one
		- Also offer this as hotkeys please: **O**riginal scale is used, **S**mall one is target, **L**arge one is target, 

### Reproduction
1. Open two videos of the same duration, dimensions and container format. Codec quality can differ. Video should be 30sec+ so that seeking/jumping can be realistically simulated.
2. Input: Seperate streams, left first.
3. Output: Left view.
4. Start playback.
5. Press hotkey "e" (as in "eye") or alternativly click the UI toggle "Swap left/right)". This works fine. As many times you like. Also if some pause and resumes are inbetween.
6. After you had ca. 10secs playback, pause.
7. Now we trigger a seek operation: Press arrow-right (seek 10 seconds forward) or arrow left.

### Actual
- From now on the synchronization between the two videos is broken. They have a time offset.

### Expected
- The videos remains in sync.
- Bino is clever enough to even handle VBR videos where the keyframe positions between video A and B may differ, by some kind of "absolute timecode instructions" to both video A and B, where relative timecodes (i.e. codec based commands like +4 inter-frames forward) fail.

### Workaround in this situation
- Press STOP.
- This resets the playhead to the start.
- Sadly it also resets the window to it's default size (you loose the maximized window state).

### Reproduction
1. Open two videos of the same size and duration. Quality can differ. Video should be min 30sec so that seeking/jumping can be realistically used.
2. Input: Seperate streams, left first
3. Output: Left view
4. Start playback
5. Press hotkey "e" (as in "eye") or alternativly click the UI toggle "Swap left/right)". This works fine. As many times you like. Also if some pause and resumes are inbetween.
6. After you had ca. 10secs playback, pause.
7. Now we trigger a seek operation: Press arrow-right (seek 10 seconds forward).

--> From now on sync is broken.

**Comment by marlam** [comment]
OK, there are several points in this one report:

1. Regarding "open multiple files via double click": that seems to be specific to Mac, which I don't use. I see no way to do that in a system independent way. You might want to contact Frédéric Devernay (who builds Bino for Mac) about this.
2. Dedicated Zoom factors: The current zoom feature is designed for casual viewing of videos, not for a comparison of video qualities in two different files. I suggest that Bino is not the right tool for this job. I would recommend using a viewer such as [qv](https://marlam.de/qv) that allows frame-by-frame analysis, and optionally producing a single video file with your desired specifications (regarding streams, zoom, cutout etc) either directly with [ffmpeg](https://ffmpeg.org/) or a frame-based tool such as [tad](https://marlam.de/tad).
3. Criteria for separate streams: These are not arbitrary, they are really technically necessary because of the way videos are stored in container formats and codecs. If these are not fulfilled, then the streams will be out of sync and there is no chance for consistent seeking. But these limitations are only in place for a video player that is optimized for linear viewing with synchronization to audio; if you use a frame-by-frame analysis tool such as [qv](https://marlam.de/qv) then the two video sources can be completely different.
4. This is related to point 3. Basically, Bino is just not written with your use case in mind. You are better off using a different tool.

**Comment by porg** [comment]
Hi @marlam,

- Ad 1: I contacted Frederic. Let's await his reaction.
- Ad 2-4: Thanks for the info. Looked at **qv** 's webpage. Does not look to me like a readymade application but rather like a toolchain for pros. First you have to compile yourself (kicks out ordinary users already) and at first glance on the screenshots looks that it has no GUI.
- I was looking for a GUI out of the box which you can throw two files at, and then have a central playback/scrubbing control which plays back both videos in sync together, and some custom zoom control for proper visual comparison. Can I expect that from **qv** and **tad**?

**Comment by marlam** [comment]
While qv has a GUI now, neither qv nor tad are probably on the level of ease of use that you expect... On the other hand, your use case is rather exotic, so I'm not sure if you can find a tool that has a GUI for what you want.

**Comment by porg** [comment]
Thanks for the info.

Exotic in the video playback world maybe. I assume not so exotic in the professional world of video encoding and streaming. Have to research more. These professionals certainly have the toolsets for analysis both subjective and objective (deduced from human perception tests). But these tools very likely are closed tools and expen$ive if I just look at what is charged by experts such as https://streaminglearningcenter.com

**Comment by devernay** [comment]
Hi!
When opening multiple files from the finder on macOS, it generates one QFileOpenEvent per file (posted [here](https://github.com/qt/qtbase/blob/5.10/src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm#L297) from Qt and handled [here](https://github.com/marlam/bino-mirror/blob/ddf9854f9dd776dd3d142870cf5e207cf29994b2/src/mainwindow.cpp#L577) in the Bino code).
As far as I know, it's not possible whether these were opened consecutively (double-click file A, then file B) or simultaneously.
It is a limitation of Qt, and we can't handle this properly, sorry.
More info: https://lists.qt-project.org/pipermail/interest/2018-January/029175.html
