### ISSUE TITLE
I tried to compile version 2.1 on macos, but the program failed to run

### ISSUE THREAD

**Issue by Darling-Lee** [marlam/bino#17]
source code version:2.1
OS version: MACOS 12.6.3
QT version:6.4.2
I have successfully compiled the binary file with cmake, but when I run it, it always prompts “Insufficient OpenGL capabilities.”. Any body can give me some help?

**Comment by marlam** [comment]
Hi, thank you for this report.

There was a bug in the OpenGL version check. It's [fixed](https://github.com/marlam/bino-mirror/commit/ff6a0d3b69a22cc53a5a2fdb147bca5419197393) now. 

Can you try again with the current version from the git repository?

**Comment by marlam** [comment]
Ok, this is confirmed to be fixed now. Thank you for your help!
