### ISSUE TITLE
Bino crashing on opening under macOS Big Sur

### ISSUE THREAD

**Issue by fdolbec123** [marlam/bino#2]
Hi!

I know that macOS Big Sur is still under development, but I wanted to try to see if Bino could work. It's working fine under the latest public beta of Catalina (using the precompiled binary from Frédéric Devernay)

Under macOS Big Sur, both the version of Frédéric and the one I compiled myself(more info of my config below) from git have the same critical bug. On opening, we can see quickly the main window but disappear right after with an error code 11 (Segmentation fault). Here is the log I get:

[Log](https://pastebin.com/DEAzKMqa)

If I try using the terminal to run the app with no GUI and no video to play, everything is fine.
If I try to play a video with no GUI by using the following command in the terminal `./Bino.app/Contents/MacOS/Bino -n --log-file=LOG --log-level=debug /Volumes/macOS/Films/Frozen.II.2019.3D.1080p.BluRay.x264-GUACAMOLE\[rarbg\]/gua-frozen2.3d-1080p.mkv`, then the app get a different log file. As you can see, the app seems to be able to parse the movie, but fails to show the movie (the movie is show for half a second and then it crashes).

Here is the log I get when try to play the movie:
[Log](https://pastebin.com/XLNXts6B)

Here is the configuration I had when building the app from source:

- macOS Big Sur dev beta 4
- homebrew (up to date)
- Latest version of texinfo (6.7), FFmpeg (4.3.1), Glew (2.1.0), LibASS(0.14.0), qt4(formally qt@4 version 4.8.7_6), openal-soft (1.20.1) and gettext (0.21)
- I choosed to build with openal-soft because OpenAL from Apple is been deprecated and only there for compatibility since at least Catalina

I had a few minor bug to fix before it could compile (fix a gettext problem with mismatching macros and two lines of code in `media_object.cpp` so it would be working with the latest version of FFmpeg).

If you want someone to test your builds, it would be a pleasure to help!

**EDIT: I put my logs on Pastebin because they would take quite a lot of space here.**

**Comment by fdolbec123** [comment]
Seems to be fixed with the new beta (dev beta 5), tho I can not guaranty it will be fine on macOS release date in fall.

**Comment by marlam** [comment]
Since there was no news on this, I'm closing this now. Please reopen if the problem persists.
