### ISSUE TITLE
Will open seperate Left/Right 3D file and output 3D Dual Screen function be include in new version？

### ISSUE THREAD

**Issue by cvtendent** [marlam/bino#22]
Thanks for your gread job.
I am trying to use you code to make my project
I am new to write code.The version 1.6.8 seem developped under linux which is not system I am working,so I have difficulty to build the version 1.6.8.
So I bulid version 2.1 by Qt in Windows.But find that open seperate Left/Right 3D file and output 3D Dual Screen function is not find in version 2.X . Will it be added in furture?

**Comment by marlam** [comment]
* Multi screen output is supported via VR mode if you build with [QVR](https://marlam.de/qvr/).
* Multi input might be added in the future depending on QtMultiMedia support.
