### ISSUE TITLE
Can't clone on Windows

### ISSUE THREAD

**Issue by ThreeDeeJay** [marlam/bino#33]
I keep getting this error when attempting to clone on Windows (on my local machine and also [GitHub Actions](https://github.com/ThreeDeeJay/bino/actions/runs/9973229432/job/27558121461#step:2:59))
```
git clone https://git.marlam.de/git/bino.git
Cloning into 'bino'...
remote: Enumerating objects: 7306, done.
remote: Counting objects: 100% (7306/7306), done.
remote: Compressing objects: 100% (2328/2328), done.
remote: Total 7306 (delta 5491), reused 6473 (delta 4933), pack-reused 0
Receiving objects: 100% (7306/7306), 2.52 MiB | 3.71 MiB/s, done.
Resolving deltas: 100% (5491/5491), done.
error: invalid path 'aux/bino-logo-big.svg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
It works on the [Ubuntu runner](https://github.com/ThreeDeeJay/bino/actions/runs/9973465376/job/27558844544#step:2:73), but I"m trying to compile Windows binaries.
Any idea what's causing this/how to fix it?

**Comment by marlam** [comment]
Should be fixed with commit b3e4dd8.

Apparently in 2024 a file or directory cannot be named aux on Windows because AUX was the name of the serial port in the days of MS-DOS.
