### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by EtienneAb3d** [marlam/bino#4]
Hi!
On XUbuntu 20.10, I got this error message at compilation time, strangely coming from standard QT lib:
```
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow:1,
                 from mainwindow.h:31,
                 from gui.h:33,
                 from dispatch.cpp:41:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h: In member function ‘bool QObject::isWindowType() const’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:154:54: error: ‘class QObjectData’ has no member named ‘ksWindow’; did you mean ‘isWindow’?
  154 |     inline bool isWindowType() const { return d_ptr->ksWindow; }
      |                                                      ^~~~~~~~
      |                                                      isWindow
```
Any idea?
Best regards,
Etienne

PS: Windows EXE version works nicely using Wine. I just had to play a bit with the sound delay.
:)

**Comment by marlam** [comment]
That is very strange, it's clearly a typo in the `qobject.h` header.

Since the difference between 'i' and 'k' is just one bit, maybe this bit flipped on your harddrive by accident? In that case it should be fixable by reinstalling `qtbase5-dev`.

**Comment by EtienneAb3d** [comment]
YES !!

Since few months, on 2 completely different XUbuntu up-to-date machines, I get instabilities. I searched a lot to find out the solution. I'm suspecting a problem with SSD NVMe (both have ones). But, it's the very first time I explicitly see a real file damage problem! :-(

The final binary is starting properly. But, when trying to open a media with "File/OpenFile(s)", I get a problem. As this is different, I will open a new issue for this.

Thanks !
