### ISSUE TITLE
Can't open a file

### ISSUE THREAD

**Issue by EtienneAb3d** [marlam/bino#5]
Compiled successfully on XUbuntu 20.10 (see #4).

The final binary is starting properly. But, when trying to open a media with "File/OpenFile(s)", I get a problem:
1. after the short information message, the file selector is opening, but stay transparent (no content, only the window framing). It is really transparent, not simply frozen. If I move it, I see the other windows through it (not simply a static initial copy of them, as it may occur some times when a window is frozen).
2. one CPU core/thread is running 100%
4. I can close this transparent Window, and the application seems to still properly be running
5. points 1 to 4 can be repeated several times

Console output is showing this:
```
bino: [wrn] Cannot initialize LIRC.
bino: [wrn] LibASS: Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
bino: [wrn] LibASS: Using font provider fontconfig
bino: [wrn] QXcbConnection: XCB error: 3 (BadWindow), sequence: 784, resource id: 13163934, major code: 40 (TranslateCoords), minor code: 0
```
The last line may be repeated when I'm trying to open a file, but not all the time. Here is a new example:
```
bino: [wrn] QXcbConnection: XCB error: 3 (BadWindow), sequence: 1046, resource id: 13174010, major code: 40 (TranslateCoords), minor code: 0
```

Any idea?

PS: "Open device(s)" is working properly. I can see my WebCam playing.

**Comment by marlam** [comment]
No idea. I cannot reproduce the problem.

Does the `bino` package in Ubuntu 20.10 work? If yes, then there's something wrong with your specific setup. If no, then maybe report a bug to them.

**Comment by EtienneAb3d** [comment]
Same problem with the official XUbuntu package.
:-/

**Comment by ansel-hub** [comment]
Hi, same problem in Void Linux, compiled from source. I don't get the (BadWindow) warning message but on trying to open a file from the program a transparent openbox frame can be seen, I can move it around and it displays my desktop, and also the cpu rises.

**Comment by marlam** [comment]
That's bad news. I still cannot reproduce the error, so I'd like to collect some more information.

What desktop environment / window manager do you use? (I assume Xubuntu uses XFCE.)
Maybe this only occurs with certain window managers.

**Comment by ansel-hub** [comment]
My desktop environment is LXDE and the window manager is Openbox

**Comment by marlam** [comment]
I still was not able to reproduce this.

Please try `bino --log-file=log.txt --log-level=debug`, maybe that produces some useful information.

If no messages labeled `[dbg]` show up in your log file, then your binary does not support debugging output. In that case, it would be helpful if you build from source and configure with `--enable-debug`.

In any case, messages labeled `[inf]` should always show up, and maybe that already helps.

**Comment by beew** [comment]
Similar issue on Ubuntu 20.04 LTS with default gnome desktop (and with Unity as well) On Gnome shell when click open files bino just freezes and turns grey, on Unity it open a transparent window. Same with bino-1.6.6 in repository and bino-1.6.7 compiled from source.


from terminal
```
bino --log-file=log.txt --log-level=debug

```

from log.txt

```
bino: [wrn] Cannot initialize LIRC.
bino: [wrn] LibASS: Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
bino: [wrn] LibASS: Using font provider fontconfig

Also terminal output
```
bino: [wrn] Qt: Session management error: Could not open network socket
```

**Comment by beew** [comment]
Similar issue on Ubuntu 20.04 LTS with default gnome desktop (and with Unity as well) On Gnome shell when click open files bino just freezes and turns grey, on Unity it open a transparent window. Same with bino-1.6.6 in repository and bino-1.6.7 compiled from source.


from terminal
```
bino --log-file=log.txt --log-level=debug

```

from log.txt

```
bino: [wrn] Cannot initialize LIRC.
bino: [wrn] LibASS: Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
bino: [wrn] LibASS: Using font provider fontconfig


```

**Comment by marlam** [comment]
Am [answer on Stackoverflow](https://stackoverflow.com/questions/986964/qt-session-management-error) and a [note by Intel](https://www.intel.com/content/www/us/en/programmable/support/support-resources/knowledge-base/solutions/rd04042012_367.html) suggest to use `unset SESSION_MANAGER` before running Bino.
Does that solve the problem? If so, the Stackoverflow answer suggests that the reason may be stale session files.

**Comment by beew** [comment]
> Am [answer on Stackoverflow](https://stackoverflow.com/questions/986964/qt-session-management-error) and a [note by Intel](https://www.intel.com/content/www/us/en/programmable/support/support-resources/knowledge-base/solutions/rd04042012_367.html) suggest to use `unset SESSION_MANAGER` before running Bino.
> Does that solve the problem? If so, the Stackoverflow answer suggests that the reason may be stale session files.

Nope, makes no difference and I don't experience this problem with other qt apps (I have many of them)

**Comment by marlam** [comment]
The three lines above were the complete content of the log file? No further messages, not even if you try to open a file from the command line (`$ bino myvideo.mp4`)?

**Comment by beew** [comment]
> The three lines above were the complete content of the log file? No further messages, not even if you try to open a file from the command line (`$ bino myvideo.mp4`)?

There is no error message if open video directly with bino as above  and it works (right click video and choose bino from context menu also works) The problem is when you start bino, then try to use open file dialogue to open a video

**Comment by marlam** [comment]
OK, let's go through the source code. Can you deactivate the Tip window in `mainwindow.cpp` lines 707-732, e.g. by changing `if (_settings...` to `if (false && _settings...`? Does that solve the problem?

**Comment by marlam** [comment]
Bino is currently being rewritten completely and will be based on Qt 6. This should fix these problems because Bino does not implement its own low level thread fiddling anymore.  An initial version of the new Bino is already in the main git repository, you can try it.
